name = "globalsync"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:worker"

[durable_objects]
bindings = [{name = "WEBSOCKET_SERVER", class_name = "WebSocketServer"}]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]

# Environment variables (set via wrangler secret or dashboard)
# [vars]
# VITE_FIREBASE_API_KEY = ""
# VITE_FIREBASE_PROJECT_ID = ""
# VITE_FIREBASE_APP_ID = ""
