name = "globalsync"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

[build]
command = "npx esbuild worker/index.ts --bundle --format=esm --outfile=dist/worker.js --external:lightningcss --external:@babel/preset-typescript/package.json"

[durable_objects]
bindings = [{name = "WEBSOCKET_SERVER", class_name = "WebSocketServer"}]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]
